services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 3s
      retries: 10

  tests:
    build:
      context: ./functionalTests
      dockerfile: Dockerfile
    depends_on:
      web:
        condition: service_healthy
    environment:
      - BASE_URL=http://web:8000
    command: ["python", "test_svelte_app.py"]
